# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{manbook}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Nicholas E. Rabenau}]
  s.date = %q{2011-12-02}
  s.description = %q{The manbook command can be used to produce an eBook from one or more man pages.}
  s.email = %q{nerab@gmx.net}
  s.executables = [%q{mktoc}, %q{manbook}, %q{manbook}]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md",
    "TODO"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "TODO",
    "VERSION",
    "bin/manbook",
    "bin/mktoc",
    "lib/manbook.rb",
    "lib/manbook/errors.rb",
    "lib/manbook/formatter.rb",
    "lib/manbook/html_formatter.rb",
    "lib/manbook/log_formatter.rb",
    "lib/manbook/parser.rb",
    "templates/_page.html.erb",
    "templates/about.html.erb",
    "templates/application.html.erb",
    "templates/index.html.erb",
    "templates/library_books.jpg",
    "templates/manbook.ncx.erb",
    "templates/manbook.opf.erb",
    "test/fixtures/bash.html",
    "test/fixtures/cat.html",
    "test/fixtures/git.html",
    "test/fixtures/gunzip.html",
    "test/fixtures/less.html",
    "test/fixtures/ls.html",
    "test/fixtures/man.html",
    "test/helper.rb",
    "test/unit/test_manbook.rb",
    "test/unit/test_mktoc.rb"
  ]
  s.homepage = %q{http://github.com/nerab/manbook}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.9}
  s.summary = %q{Produces an eBook from man pages}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<open4>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_development_dependency(%q<rake>, ["= 0.8.7"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
    else
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<open4>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<rake>, ["= 0.8.7"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<open4>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<rake>, ["= 0.8.7"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
  end
end

